### ISSUE TITLE
Please dot not make the shared lib path a dot directory

### ISSUE THREAD

**Issue by kseistrup** [nbittich/adana#60]
```sh
» adana
adana v0.17.3 (rust version: 1.76)
shared lib path: "~/.local/share/.libs_adana"

Db Path: ~/.local/share/.adanadb/adana.db
[DEFAULT~]
```

In my opinion the `.libs_adana` part should (1) _not_ be a dot directory, but a fully visible directory, and (2) just carry the name `adana`: `~/.local/share/adana`

----

edit: typo

**Comment by nbittich** [comment]
Sounds reasonable, thanks for your suggestion! I'll try to work on it next week.

**Comment by kseistrup** [comment]
I see now that there is also a `~/.local/share/adanadb/` directory. My original argument goes for this, too: please put everything in the same visible directory: `~/.local/share/adana/`. If the database needs separation from the shared lib, add one of more subdirectories, e.g. `~/.local/share/adana/db/` and `~/.local/share/adana/lib/`.

**Comment by nbittich** [comment]
Thanks, I've applied your suggestions. It will land in the next version that I'm about to release (0.17.4)
